server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/resorts"
    username: mayastelzer
    password:
  thymeleaf:
    cache: false

devtools:
  livereload:
    enabled: true
logging:
  level:
    root: trace
