server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://db-server:5432/skiing"
    username: skiing_user
    password:
  thymeleaf:
    cache: false