server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/skiing"
    username: maya
    password: password1
  thymeleaf:
    cache: false

devtools:
  livereload:
    enabled: true

